name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          
          # base
          base: header, activity, community, repositories, metadata
          
          # achievement
          plugin_achievements: yes
          plugin_achievements_threshold: X

          # activity
          plugin_activity: yes
          plugin_activity_timestamps: yes
          plugin_activity_limit: 10
          plugin_activity_load: 1000
          plugin_activity_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]

          # code snippet
          plugin_code: yes

          # discussion
          plugin_discussions: yes
