name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          
          # config
          config_timezone : Asia/Jakarta
          config_display: large
          extras_css: |
            h2 {
              color: black;
              font-size: 20px;
              font-weight: bold;
            }
          retries: 3
          retries_delay: 300
          
          # base
          base: header, activity, community, repositories, metadata
          
          # introduction
          plugin_introduction: yes
          user: andre-fajar-n
          
          # achievement
          plugin_achievements: yes
          plugin_achievements_threshold: X

          # activity
          plugin_activity: yes
          plugin_activity_timestamps: yes
          plugin_activity_limit: 10
          plugin_activity_load: 1000
          plugin_activity_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]

          # code snippet
          plugin_code: yes

          # discussion
          plugin_discussions: yes
          
          # follow up pull request
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          
          # gists
          plugin_gists: yes
          
          # coding habits
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes
          
          # isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # language
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: true
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_recent_days: 365
          
          # licenses
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_licenses_ratio: true
          
          # line of code
          plugin_lines: yes
          
          # notable
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, pull_request, issue
          
          # people
          plugin_people: yes
          plugin_people_shuffle: yes
          
          # reactions
          plugin_reactions: yes
          plugin_reactions_details: count, percentage
          
          # skyline
          plugin_skyline: yes
          plugin_skyline_quality: 1
          
          # repo traffic
          plugin_traffic: yes
          
          # topics
          plugin_topics: yes
          plugin_topics_sort: random
          plugin_topics_limit: 20
          plugin_topics_mode: mastered

          # recently star
          plugin_stars: yes
          plugin_stars_limit: 10
          
          # website performance
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://andrefajarn.vercel.app
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          
          # stackoverflow
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 14982832
          plugin_stackoverflow_sections: answers-top, answers-recent, questions-top, questions-recent
          plugin_stackoverflow_limit: 5
          
          # wakatime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 10
          plugin_wakatime_user: andrefn
