name: Generate Metrics Image
on:
  # Schedule daily updates
  schedule: [{cron: "30 17 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@vlatest
        with:
          token: ${{ secrets.GH_TOKEN }}

          # config
          config_timezone : Asia/Jakarta
          config_display: large
          extras_css: |
            h2 {
              color: black;
              font-size: 20px;
              font-weight: bold;
            }
          retries: 3
          retries_delay: 600

          # base
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          repositories_batch: 10
          repositories_affiliations: owner, collaborator, organization_member

          # introduction
          plugin_introduction: yes
          user: andre-fajar-n

          # achievement
          plugin_achievements: yes

          # activity
          plugin_activity: yes
          plugin_activity_timestamps: yes
          plugin_activity_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_activity_days: 365
          plugin_activity_limit: 10

          # commit calendar
          plugin_calendar: yes
          plugin_calendar_limit: 0

          # follow up pull request
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes

          # coding habits
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes

          # isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # language activity
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: true
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_recent_days: 365
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15

          # line of code
          plugin_lines: yes
          plugin_lines_sections: base, repositories, history
          plugin_lines_repositories_limit: 10
          plugin_lines_history_limit: 0

          # notable
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, pull_request, issue
          plugin_notable_self: yes

          # people
          plugin_people: yes
          plugin_people_shuffle: yes

          # skyline
          plugin_skyline: yes
          plugin_skyline_quality: 1
          plugin_skyline_frames: 120
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }

          # repo traffic
          plugin_traffic: yes

          # topics
          plugin_topics: yes
          plugin_topics_sort: starred
          plugin_topics_limit: 20
          plugin_topics_mode: mastered

          # recently star
          plugin_stars: yes
          plugin_stars_limit: 10

          # wakatime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 10

          # leetcode
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
