name: GitHub-Profile-3D-Contrib

on:
  schedule: # 17:00 UTC
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name readme-bot
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A .
          git commit -m "generated profile 3D"
          git push
