name: Update Wakatime Data

on:
  schedule:
    # Runs at 19:30 UTC
    - cron: '30 19 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "True"
          SHOW_LANGUAGE: "True"
          # LOCALE: "en"
